// adapted from https://siegelgale.com/brand-naming-8-great-fake-company-names/ and https://docs.google.com/spreadsheets/d/1_dufcz2dyzWRDmdUlbLKYB5YJL_x-z-SQRlmya2nLAo/edit#gid=0
export const randomOrganizations: string[] = [
	`Acme Corporation`,
	`Globex Corporation`,
	`Soylent Corp`,
	`Initech`,
	`Bluth Company`,
	`Umbrella Corporation`,
	`Hooli`,
	`Vehement Capital Partners`,
	`Massive Dynamic`,
	`Wonka Industries`,
	`Stark Industries`,
	`Gekko & Co`,
	`Wayne Enterprises`,
	`Bubba Gump`,
	`Cyberdyne Systems`,
	`Genco Pura Olive Oil Company`,
	`The New York Inquirer`,
	`Duff Beer`,
	`Olivia Pope & Associates`,
	`Sterling Cooper`,
	`Ollivander's Wand Shop`,
	`Cheers`,
	`Krusty Krab`,
	`Good Burger`,
	`Burns Industries`,
	`Dunder Mifflin, Inc.`,
	`E Corp`,
	`Hooli`,
	`Los Pollos Hermanos`,
	`Stark Industries`,
	`Wayne Enterprises, Inc.`,
	`Axe Capital`,
	`Delos Inc`,
	`Iron Bank of Braavos`,
	`Rearden Steel `,
	`Aperture Science`,
	`Aviato`,
	`Monsters, Inc.`,
	`Rainholm Industries`,
	`Umbrella Corp`,
	`Bailey Building and Loan Association`,
	`Bayside High School`,
	`Black Mesa`,
	`Blue Cat Hotel`,
	`Cyberdyne Systems Corp.`,
	`Duke & Duke`,
	`Entertainment 720`,
	`Genco Pura Olive Oil Company`,
	`Globex`,
	`Gregarious Simulation Systems`,
	`Hooper's Store`,
	`InGen`,
	`Fang and Bone`,
	`Macmillan Toys`,
	`MomCorp `,
	`NERV`,
	`Oceanic Airlines`,
	`Omni Consumer Products`,
	`Oscorp `,
	`Paper Street Soap Company`,
	`Parker Industries`,
	`Pearson Specter Litt`,
	`Pied Piper`,
	`PolyCon`,
	`Prestige Worldwide`,
	`Rekall`,
	`Relaxicab`,
	`Rent a Swag`,
	`Sirius Cybernetics Corp.`,
	`Springfield Nuclear Power Plant`,
	`Sterling Cooper`,
	`Stratton Oakmont`,
	`TelAmeriCorp`,
	`The Bluth Company`,
	`The Estelle Leonard Talent Agency`,
	`The Very Big Corporation of America`,
	`Tyrell Corp. `,
	`Veridian Dynamics`,
	`Yubaba`,
	`Weyland Yutani`,
	`Rand Enterprises`
];

export const randomNames: [string, string][] = [
	['Malcolm', 'Reynolds'],
	['Zoe', 'Washburne'],
	['Hoban', 'Washburne'],
	['Inara', 'Serra'],
	['Jayne', 'Cobb'],
	['Kaylee', 'Frye'],
	['Simon', 'Tam'],
	['River', 'Tam'],
	['Derrial', 'Book'],
	['Jubal', 'Early'],
	['Daniel', 'Ocean'],
	['Robert Rusty', 'Ryan'],
	['Frank', 'Catton'],
	['Reuben', 'Tishkoff'],
	['Virgil', 'Malloy'],
	['Saul', 'Bloom'],
	['Linus', 'Caldwell'],
	['Terry', 'Benedict'],
	['Basher', 'Tarr'],
	['Turk', 'Malloy'],
	['Livingston', 'Dell'],
	['Billy Tim', 'Denham'],
	['Tess', 'Ocean'],
	['Bucky', 'Buchanan'],
	['Isabel', 'Lahiri'],
	['Roman', 'Nagel'],
	['Ian Nicholas', 'McNally'],
	['Denny', 'Shields'],
	['Gaspar', 'LeMarque'],
	['Abigail', 'Sponder'],
	['Greco', 'Montgomery'],
	['Slevin', 'Kelevra'],
	['Ichabod', 'Crane'],
	['Jean', 'Pargetter'],
	['Lionel', 'Hardcastle'],
	['Judith', 'Hanson'],
	['Alistair', 'Deacon'],
	['Sandy', 'Edwards'],
	['Rocky', 'Hardcastle'],
	['Madge', 'Hardcastle'],
	['Penny', 'Johnson'],
	['Stephen', 'Johnson'],
	['Jonathan', 'Masbath'],
	['Tracey', 'Smith'],
	['Ben', 'Harper'],
	['Nick', 'Harper'],
	['Michael', 'Harper'],
	['Susan', 'Harper'],
	['Alice', 'Longbottom'],
	['Amos', 'Diggory'],
	['Andromeda', 'Black'],
	['Angelina', 'Johnson'],
	['Arabella', 'Figg'],
	['Argus', 'Filch'],
	['Arthur', 'Weasley'],
	['Augusta', 'Longbottom'],
	['Bartemius', 'Crouch'],
	['Belatrix', 'Black'],
	['Bellatrix', 'Lestrange'],
	['Bertha', 'Jorkins'],
	['Bertie', 'Bott'],
	['Bill', 'Weasley'],
	['Birtha', 'Jorkins'],
	['Blaise', 'Zabini'],
	['Bob', 'Ogden'],
	['Cedric', 'Diggory'],
	['Charlie', 'Weasley'],
	['Cho', 'Chang'],
	['Colin', 'Creevy'],
	['Cormac', 'McLaggen'],
	['Cornelious', 'Fudge'],
	['Dean', 'Thomas'],
	['Dedulus', 'Diggle'],
	['Dennis', 'Creevey'],
	['Duddly', 'Dersly'],
	['Eloise', 'Midgeon'],
	['Emmaline', 'Vance'],
	['Ernie', 'Mcmillan'],
	['Ernie', 'Prang'],
	['Filius', 'Flitwick'],
	['Finius', 'Nigelus'],
	['Fleur', 'Delacour'],
	['Florean', 'Fortesque'],
	['Frank', 'Bryce'],
	['Fred', 'Weasley'],
	['Gabrielle', 'Delacour'],
	['George', 'Weasley'],
	['Gildaroy', 'Lockheart'],
	['Ginny', 'Weasley'],
	['Godric', 'Gryffindor'],
	['Graham', 'Pritchard'],
	['Gwenog', 'Jones'],
	['Hannah', 'Abbott'],
	['Helga', 'Hufflepuff'],
	['Hermione', 'Granger'],
	['Herold', 'Dingle'],
	['Igor', 'Karkaroff'],
	['James', 'Potter'],
	['Katie', 'Bell'],
	['Kingsley', 'Shacklebolt'],
	['Lavender', 'Brown'],
	['Lily', 'Potter'],
	['Lucius', 'Malfoy'],
	['Ludo', 'Bagman'],
	['Luna', 'Lovegood'],
	['Poppey', 'Pomfrey'],
	['Malcolm', 'Baddock'],
	['Marcus', 'Belby'],
	['Marcus', 'Flint'],
	['Marge', 'Dursley'],
	['Marietta', 'Edgecome'],
	['Marvalo', 'Gaunt'],
	['Merope', 'Gaunt'],
	['Millicent', 'Bagnold'],
	['Millicent', 'Bulstrode'],
	['Minerva', 'McGonagall'],
	['Molly', 'Weasley'],
	['Morfin', 'Gaunt'],
	['Mundungus', 'Fletcher'],
	['Narcissa', 'Malfoy'],
	['Neville', 'Longbottom'],
	['Nicholas', 'Flamel'],
	['Nymphadora', 'Tonks'],
	['Oliver', 'Wood'],
	['Otto', 'Bagman'],
	['Padma', 'Patil'],
	['Parvatie', 'Patil'],
	['Penelope', 'Clearwater'],
	['Percy', 'Weasley'],
	['Petunia', 'Dursley'],
	['Remus', 'Lupin'],
	['Roger', 'Davies'],
	['Romilda', 'Vane'],
	['Ron', 'Weasley'],
	['Rowena', 'Ravenclaw'],
	['Rubeus', 'Hagrid'],
	['Rufus', 'Scrimgeour'],
	['Salazar', 'Slytherin'],
	['Seamus', 'Finnigan'],
	['Sirius', 'Black'],
	['Susan', 'Bones'],
	['Viktor', 'Krum'],
	['Miles', 'Massey'],
	['Marylin', 'Hamilton Rexroth Doyle Massey'],
	['Donovan', 'Donaly'],
	['Gus', 'Petch'],
	['Rex', 'Rexroth'],
	['Freddy', 'Bender'],
	['Howard D.', 'Doyle'],
	['Bonnie', 'Donaly'],
	['Wheezy', 'Joe'],
	['Sarah', 'Sorkin'],
	['Ollie', 'Olerud'],
	['Jack', 'Sparrow'],
	['Angelica', 'Teach'],
	['Hector', 'Barbossa'],
	['Joshamee', 'Gibbs'],
	['Will', 'Turner'],
	['Elizabeth', 'Swann'],
	['James', 'Norrington'],
	['Davy', 'Jones'],
	['Weatherby', 'Swann'],
	['Tia', 'Dalma'],
	['Derek', 'Zoolander'],
	['Matilda', 'Jeffries'],
	['Jacobim', 'Mugatu'],
	['Katinka', 'Ingabogovinanana'],
	['Maury', 'Ballstein'],
	['J.P.', 'Prewitt'],
	['Larry', 'Zoolander'],
	['Scrappy', 'Zoolander'],
	['Frasier', 'Crane'],
	['Niles', 'Crane'],
	['Daphne', 'Moon'],
	['Roz', 'Doyle'],
	['Martin', 'Crane'],
	['Bulldog', 'Briscoe'],
	['Kenny', 'Daly'],
	['Gil', 'Chesterton'],
	['Noel', 'Shempsky'],
	['Donny', 'Douglas'],
	['Lilith', 'Sternin'],
	['Bebe', 'Glazer'],
	['Dr. Mel', 'Karnofsky'],
	['Julia', 'Wilcox'],
	['Frederick', 'Crane'],
	['Simon', 'Moon'],
	['Lana', 'Gardner'],
	['Kirby', 'Gardner'],
	['Sherry', 'Dempsey'],
	['Kate', 'Costas'],
	['Faye', 'Moskowitz'],
	['Diane', 'Chambers'],
	['Claire', 'French'],
	['Cassandra', 'Stone'],
	['Cam', 'Winston'],
	['Samantha', 'Pierce'],
	['Regan', 'Shaw'],
	['William', 'Tewksbury'],
	['Hester', 'Crane'],
	['Cora', 'Winston'],
	['Honey', 'Snow'],
	['Lorelai', 'Gilmore'],
	['Rory', 'Gilmore'],
	['Sookie', 'St. James'],
	['Lane', 'Kim'],
	['Michel', 'Gerard'],
	['Luke', 'Danes'],
	['Emily', 'Gilmore'],
	['Richard', 'Gilmore'],
	['Paris', 'Geller'],
	['Jess', 'Mariano'],
	['Kirk', 'Gleason'],
	['Jason', 'Stiles'],
	['Jackson', 'Belleville'],
	['Max', 'Medina'],
	['Marty', 'McFly'],
	['Emmett', 'Brown'],
	['Lorraine', 'Baines'],
	['George', 'McFly'],
	['Biff', 'Tannen'],
	['Jennifer', 'Parker'],
	['Dave', 'McFly'],
	['Linda', 'McFly'],
	['Goldie', 'Wilson'],
	['Andy', 'Dufresne'],
	['Red', 'Redding'],
	['Vincent', 'Vega'],
	['Jules', 'Winnfield'],
	['Butch', 'Coolidge'],
	['Marsellus', 'Wallace'],
	['Mia', 'Wallace'],
	['Forrest', 'Gump'],
	['Nino', 'Quincampoix'],
	['Amandine', 'Poulain'],
	['Raymond', 'Dufayel'],
	['Dominique', 'Bretodeau'],
	['Jeffrey', 'Lebowski'],
	['Walter', 'Sobchak'],
	['Maude', 'Lebowski'],
	['Donny', 'Kerabatsos'],
	['Bunny', 'Lebowski'],
	['Jesus', 'Quintana'],
	['Nancy', 'Callahan'],
	['Will', 'Hunting'],
	['Sean', 'Maguire'],
	['Chuckie', 'Sullivan'],
	['Gerald', 'Lambeau'],
	['Billy', 'McBride'],
	['Lionel', 'Logue'],
	['Gordie', 'Lachance'],
	['Chris', 'Chambers'],
	['Teddy', 'Duchamp'],
	['Vern', 'Tessio'],
	['Ace', 'Merrill'],
	['Billy', 'Tessio'],
	['Charlie', 'Hogan'],
	['Eyeball', 'Chambers'],
	['Logain', 'Ablar'],
	['Lelaine', 'Akashi'],
	['Perrin', 'Aybara'],
	['Faile', 'Bashere'],
	['Davram', 'Bashere'],
	['Gareth', 'Bryne'],
	['Mat', 'Cauthon'],
	['Galad', 'Damodred'],
	['Moiraine', 'Damodred'],
	['Lan', 'Mandragoran'],
	['Min', 'Farshaw'],
	['Damer', 'Flinn'],
	['Artur', 'Hawkwing'],
	['Seaine', 'Herimon'],
	['Tigraine', 'Mantear'],
	['Cadsuane', 'Melaidhrin'],
	['Thom', 'Merrilin'],
	['Ilyena', 'Moerelle'],
	['Fedwin', 'Morr'],
	['Pedron', 'Niall'],
	['Siuan', 'Sanche'],
	['Juilin', 'Sandar'],
	['Birgitte', 'Silverbow'],
	['Elayne', 'Trakand'],
	['Gawyn', 'Trakand'],
	['Morgase', 'Trakand'],
	['Dexter', 'Haven'],
	['Tracy', 'Lord'],
	['Macaulay', 'Connor'],
	['Elizabeth', 'Imbrie'],
	['George', 'Kittredge'],
	['Seth', 'Lord'],
	['Margaret', 'Lord'],
	['Dinah', 'Lord'],
	['Sidney', 'Kidd'],
	['Chris', 'Hughes'],
	['Kate', 'Erickson'],
	['David', 'Stern'],
	['Edward', 'Johnston'],
	['Philip J.', 'Fry'],
	['Turanga', 'Leela'],
	['Bender', 'Rodriguez'],
	['Professor', 'Farnsworth'],
	['Doctor', 'Zoidberg'],
	['Amy', 'Wong'],
	['Hermes', 'Conrad'],
	['Zapp', 'Brannigan'],
	['Kif', 'Kroker'],
	['Roy', 'Trenneman'],
	['Maurice', 'Moss'],
	['Jen', 'Barber'],
	['Douglas', 'Reynholm'],
	['Denholm', 'Reynholm'],
	['John Hannibal', 'Smith'],
	['Templeton', 'Peck'],
	['B.A.', 'Baracus'],
	['H.M.', 'Murdock'],
	['Colonel', 'Lynch'],
	['Roderick', 'Decker'],
	['Harlan', 'Fullbright'],
	['Hunt', 'Stockwell'],
	['Charissa', 'Sosa'],
	['Vance', 'Burress'],
	['Steve', 'Rogers'],
	['Peggy', 'Carter'],
	['James Bucky', 'Barnes'],
	['Howard', 'Stark'],
	['Chester', 'Phillips'],
	['Johann', 'Schmidt'],
	['Tony', 'Stark'],
	['James Rhodey', 'Rhodes'],
	['Happy', 'Hogan'],
	['Bruce', 'Banner'],
	['Natasha', 'Romanoff'],
	['Phil', 'Coulson'],
	['Clint', 'Barton'],
	['Maria', 'Hill'],
	['Erik', 'Selvig'],
	['Nick', 'Fury'],
	['Pepper', 'Potts'],
	['Justin', 'Hammer'],
	['Ivan', 'Vanko'],
	['Christine', 'Everhart'],
	['Aldrich', 'Killian'],
	['Maya', 'Hansen'],
	['Eric', 'Savin'],
	['Trevor', 'Slattery'],
	['Jane', 'Foster'],
	['Darcy', 'Lewis'],
	['Martin Q.', 'Blank'],
	['Debi', 'Newberry'],
	['Paul', 'Spericki'],
	['Felix', 'La PuBelle'],
	['Mitch', 'Martin'],
	['Frank', 'Ricard'],
	['Beanie', 'Campbell'],
	['Gordon', 'Pritchard'],
	['Lara', 'Campbell'],
	['Emmett', 'Richmond'],
	['Julie', 'Morton'],
	['Amy', 'Stone'],
	['Everett', 'Stone'],
	['Kelly', 'Stone'],
	['Meredith', 'Morton'],
	['Ben', 'Stone'],
	['Brad', 'Stevenson'],
	['Ron', 'Burgundy'],
	['Veronica', 'Corningstone'],
	['Brian', 'Fantana'],
	['Brick', 'Tamland'],
	['Champ', 'Kind'],
	['Ed', 'Harken'],
	['Garth', 'Holliday'],
	['Maxwell', 'Smart'],
	['Elle', 'Woods'],
	['Vivian', 'Kensington'],
	['Daniel', 'Collins'],
	['Kate', 'Collins '],
	['Edmund', 'Collins '],
	['Liz', 'Lemon'],
	['Tracy', 'Jordan'],
	['Jenna', 'Maroney'],
	['Kenneth', 'Parcell'],
	['Pete', 'Hornberger'],
	['Frank', 'Rossitano'],
	['Jack', 'Donaghy'],
	['Chazz Michael', 'Michaels'],
	['Jimmy', 'MacElroy'],
	['Stranz', 'van Waldenberg'],
	['Fairchild ', 'van Waldenberg'],
	['Katie', 'van Waldenberg'],
	['Ricky', 'Bobby'],
	['Cal', 'Naughton Jr.'],
	['Jean', 'Girard'],
	['Reese', 'Bobby'],
	['Lucius', 'Washington'],
	['Carley', 'Bobby'],
	['Lucy', 'Bobby'],
	['Larry', 'Dennit Jr.'],
	['John', 'Beckwith'],
	['Jeremy', 'Grey'],
	['Claire', 'Cleary'],
	['Gloria', 'Cleary'],
	['Kathleen', 'Cleary'],
	['Todd', 'Cleary'],
	['Sack', 'Lodge '],
	['Fran', 'Fine'],
	['Maxwell', 'Sheffield'],
	['C.C.', 'Babcock'],
	['Sylvia', 'Fine'],
	['Val', 'Toriello'],
	['Morty', 'Fine'],
	['Heather', 'Biblow'],
	['Danny', 'Imperiali'],
	['Charlie', 'Harper '],
	['Jake', 'Harper'],
	['Jake', 'Harper'],
	['Rachel', 'Green'],
	['Monica', 'Geller'],
	['Joey', 'Tribbiani'],
	['Chandler', 'Bing'],
	['Ross', 'Geller'],
	['Phoebe', 'Buffay'],
	['Regina', 'Phalange'],
	['Jack', 'Geller '],
	['Janice', 'Litman'],
	['Frank', 'Buffay Jr.'],
	['Tag', 'Jones'],
	['Mr.', 'Heckles'],
	['Nora', 'Tyler Bing'],
	['Eddie', 'Menuek'],
	['Gavin', 'Mitchell'],
	['Jill', 'Green'],
	['Amy', 'Green'],
	['Hoshi', 'Sato'],
	['Charles', 'Tucker III'],
	['Dr. Arik', 'Soong'],
	['Elizabeth', 'Cutler '],
	['Alex', 'Garrett'],
	['Bobbie', 'Morganstern'],
	['Gina', 'Tribbiani'],
	['Benjamin', 'Lockwood'],
	['Richard', 'Castle'],
	['Kate', 'Beckett'],
	['Martha', 'Rodgers'],
	['Javier', 'Esposito'],
	['Lanie', 'Parish'],
	['Kevin', 'Ryan'],
	['Roy', 'Montgomery'],
	['Victoria', 'Gates'],
	['Alexis', 'Castle'],
	['Patrick', 'Jane '],
	['Teresa', 'Lisbon'],
	['Kimball', 'Cho'],
	['Wayne', 'Rigsby'],
	['Grace', 'van Pelt'],
	['Madeleine', 'Hightower'],
	['Virgil', 'Minelli'],
	['Gale', 'Bertram'],
	['J.J.', 'LaRoche'],
	['Luther', 'Wainwright'],
	['Summer', 'Edgecombe'],
	['Sam', 'Bosco'],
	['Bret', 'Stiles'],
	['Tommy', 'Volker'],
	['Karen', 'Cross'],
	['Erica', 'Flynn'],
	['Ryan', 'King'],
	['Lauren', 'Schneider'],
	['Leonard', 'Hofstadter'],
	['Sheldon', 'Cooper'],
	['Howard', 'Wolowitz'],
	['Raj', 'Koothrappali'],
	['Priya', 'Koothrappali'],
	['Bernadette', 'Rostenkowski'],
	['Stuart', 'Bloom'],
	['Kathleen Kiki', 'Harrison'],
	['Lee', 'Phillips'],
	['Gwen', 'Harrison'],
	['Eddie', 'Thomas'],
	['Hector', 'Gorgonzolas'],
	['Dave', 'Kingman'],
	['Hal', 'Weidmann'],
	['Celine', 'Naville'],
	['Robert', 'Lewis'],
	['Frank', 'Naville'],
	['Tod', 'Johnson'],
	['Jason', 'Nesmith'],
	['Gwen', 'DeMarco'],
	['Alexander', 'Dane'],
	['Fred', 'Kwan'],
	['Guy', 'Fleegman'],
	['John', 'Spartan'],
	['Simon', 'Phoenix'],
	['Lenina', 'Huxley'],
	['Steven', 'Hiller'],
	['Thomas J.', 'Whitmore'],
	['David', 'Levinson'],
	['Julius', 'Levinson'],
	['Russell', 'Casse'],
	['Constance', 'Spano'],
	['Jasmine', 'Dubrow'],
	['Tom', 'Dobbs'],
	['Jack', 'Menken'],
	['Eleanor', 'Green'],
	['Eddie', 'Langston'],
	['Donald', 'Tilson'],
	['Jack', 'Hall'],
	['Sam', 'Hall'],
	['Laura', 'Chapman'],
	['Jason', 'Evans'],
	['Frank', 'Harris'],
	['Lucy', 'Hall'],
	['Janet', 'Tokada'],
	['Terry', 'Rapson'],
	['Tom', 'Gomez'],
	['Maggie', 'Carpenter'],
	['Ike', 'Graham'],
	['Ellie', 'Graham'],
	['Bob', 'Kelly'],
	['Gill', 'Chavez'],
	['Cory', 'Flemming'],
	['Dave', 'Kovic'],
	['Ellen', 'Mitchell'],
	['Bob', 'Alexander'],
	['Alan', 'Reed'],
	['Duane', 'Stevenson'],
	['Murray', 'Blum'],
	['Sam', 'Witwicky'],
	['Mikaela', 'Banes'],
	['Maggie', 'Madsen'],
	['Ron', 'Witwicky'],
	['Judy', 'Witwicky'],
	['Bob', 'Parr'],
	['Bob', 'Parr'],
	['Lucius', 'Best'],
	['Buddy', 'Pine'],
	['Dashiell', 'Parr'],
	['Violet', 'Parr'],
	['Edna', 'Mode'],
	['Esmerelda', 'Weatherwax'],
	['Gytha', 'Ogg'],
	['Tiffany', 'Aching'],
	['Samuel', 'Vimes'],
	['Sybil', 'Vimes '],
	['Carrot', 'Ironfoundersson'],
	['Delphine', 'Angua'],
	['Fred', 'Colon'],
	['Nobby', 'Nobbs'],
	['Cheery', 'Littlebottom'],
	['Reginald', 'Shoe'],
	['Mustrum', 'Ridcully'],
	['Havelock', 'Vetinari'],
	['Ponder', 'Stibbons'],
	['Eskarina', 'Smith'],
	['Windle', 'Poons'],
	['Perspicacia', 'Tick'],
	['Annagramma', 'Hawkin'],
	['Granny', 'Aching'],
	['Alberto', 'Malich'],
	['Susan', 'Sto Helit'],
	['Bartleby', 'Gaines'],
	['Sherman', 'Schrader'],
	['Daryl', 'Holloway'],
	['Rory', 'Thayer'],
	['Ben', 'Lewis'],
	['Monica', 'Moreland'],
	['Jack', 'Gaines'],
	['Diane', 'Gaines'],
	['Lizzie', 'Gaines'],
	['Abernathy Darwin', 'Dunlap'],
	['Ben', 'Lewis'],
	['Hoyt', 'Ambrose'],
	['Richard', 'van Horne'],
	['Howard', 'Brackett'],
	['Emily', 'Montgomery'],
	['Peter', 'Malloy'],
	['Cameron', 'Drake'],
	['Berniece', 'Brackett'],
	['Frank', 'Brackett'],
	['Tom', 'Halliwell'],
	['Walter', 'Brackett'],
	['Thomas', 'Crown'],
	['Catherine', 'Banning'],
	['Michael', 'McCann'],
	['Korben', 'Dallas'],
	['Jean-Baptiste Emanuel', 'Zorg'],
	['Vito', 'Cornelius'],
	['Ruby', 'Rhod'],
	['Jonathan', 'Archer'],
	['Malcolm', 'Reed'],
	['Travis', 'Mayweather'],
	['Maxwell', 'Forrest'],
	['Jess', 'Day'],
	['Nick', 'Miller'],
	['Winston', 'Bishop'],
	['Cece', 'Parekh'],
	['Phil', 'Dunphy'],
	['Claire', 'Dunphy'],
	['Haley', 'Dunphy'],
	['Alexandria', 'Dunphy'],
	['Luke', 'Dunphy'],
	['Jay', 'Pritchett'],
	['Gloria', 'Pritchett'],
	['Manny', 'Delgado'],
	['Mitchell', 'Pritchett'],
	['Cameron', 'Tucker'],
	['Peter', 'Diamond'],
	['Keith', 'Halliwell'],
	['Paul', 'Gilbert'],
	['John', 'Leaman'],
	['Georgina', 'Dallymore'],
	['Henrietta', 'Mallin'],
	['Philip', 'Banks'],
	['Carlton', 'Banks'],
	['Hilary', 'Banks'],
	['Ashley', 'Banks'],
	['Vivian', 'Banks'],
	['Arlen', 'Bales'],
	['Renna', 'Tanner'],
	['Leesha', 'Paper'],
	['Christopher', 'Chant'],
	['Eric', 'Chant'],
	['Gwendolen', 'Chant'],
	['Janet', 'Chant'],
	['Julia', 'Chant'],
	['Roger', 'Chant'],
	['Millie', 'Chant'],
	['Mordecai', 'Roberts'],
	['Tonino', 'Montana'],
	['Paolo', 'Montana'],
	['Sophie', 'Hatter'],
	['Howl', 'Pendragon'],
	['Lettie', 'Hatter'],
	['Martha', 'Hatter'],
	['Annabel', 'Fairfax'],
	['Martin', 'Banks'],
	['Duane', 'Murphy'],
	['Rico', 'Doretti'],
	['Tanja', 'Doretti'],
	['Sophie', 'Haas'],
	['Hans', 'Zielonka'],
	['Hannes', 'Haas'],
	['Arndt', 'Bechermann'],
	['Andreas', 'Zielonka'],
	['Qiang', 'Shi'],
	['Gwendolyn', 'Shepherd'],
	['Gideon', 'de Villiers'],
	['Charlotte', 'Montrose'],
	['Grace', 'Shepherd'],
	['Nick', 'Shepherd'],
	['Caroline', 'Shepherd'],
	['Arista', 'Montrose'],
	['Glenda', 'Montrose'],
	['Madeleine', 'Montrose'],
	['Falk', 'de Villiers'],
	['Thomas', 'George'],
	['Jacob', 'White'],
	['Leopold', 'Marley'],
	['William', 'Whitman'],
	['Leslie', 'Hay'],
	['Raphael', 'Bertelin'],
	['James August Peregrin', 'Pimplebottom'],
	['W.', 'Bernhard'],
	['Margret', 'Tilney'],
	['Lucy', 'Montrose'],
	['Paul', 'de Villiers'],
	['Miroslav Alexander Leopold', 'Rakoczy'],
	['Lucas', 'Montrose'],
	['Meggie', 'Folchart'],
	['Mortimer', 'Folchart'],
	['Resa', 'Folchart'],
	['Elinor', 'Loredan'],
	['Guybrush', 'Threepwood'],
	['Elaine', 'Marley '],
	['Herman', 'Toothrot'],
	['Rapp', 'Scallion'],
	['Bill', 'Fettucini'],
	['Alfredo', 'Fettucini'],
	['Largo', 'LaGrande'],
	['Kate', 'Capsize'],
	['Rum', 'Rogers Jr.'],
	['Augustus', 'DeWatt'],
	['Charmain', 'Baker'],
	['Peter', 'Regis'],
	['Conrad', 'Tesdinic'],
	['Anthea', 'Tesdinic'],
	['Ender', 'Wiggin'],
	['Hyrum', 'Graff'],
	['Bonzo', 'Madrid'],
	['Mazer', 'Rackham'],
	['Sally', 'Linsay'],
	['Monica', 'Jensson'],
	['Helen', 'Green'],
	['Rod', 'Green'],
	['Douglas', 'Black'],
	['Maggie', 'Kauffman'],
	['Nelson', 'Azikiwe'],
	['Christopher John Francis', 'Boone'],
	['Ed', 'Boone'],
	['Judy', 'Boone'],
	['Nikki', 'Heat '],
	['Jameson', 'Rook'],
	['Charles', 'Montrose'],
	['Lauren', 'Parry'],
	['Margaret', 'Rook'],
	['Peter', 'Brown'],
	['Pietro', 'Brwna'],
	['Locke', 'Lamora'],
	['Jean', 'Tannen'],
	['Calo', 'Sanza'],
	['Galdo', 'Sanza'],
	['Lukas', 'Fehrwight'],
	['Sherlock', 'Holmes'],
	['Irene', 'Adler'],
	['John', 'Watson'],
	['Greg', 'Lestrade'],
	['Mycroft', 'Holmes'],
	['Jim', 'Moriarty'],
	['Verbal', 'Kint'],
	['Fred', 'Fenster'],
	['Todd', 'Hockney'],
	['Dean', 'Keaton'],
	['Michael', 'McManus'],
	['Dave', 'Kujan'],
	['Avi', 'Denovitz'],
	['Boris', 'Yurinov'],
	['Danny', 'Meehan'],
	['Bob', 'Likely'],
	['Jake', 'Green'],
	['Henry', 'Blackwood'],
	['Mary', 'Morstan'],
	['Simza', 'Heron'],
	['Algernon', 'Moncrieff'],
	['Jack', 'Worthing'],
	['Ernest', 'Worthing'],
	['Gwendolen', 'Fairfax'],
	['Cecily', 'Cardew'],
	['Augusta', 'Bracknell'],
	['Val', 'Resnick'],
	['Lynn', 'Porter'],
	['Arthur', 'Stegman'],
	['Sinclair', 'Rutherford'],
	['Meggan', 'Sloan'],
	['Jake', 'Peralta'],
	['Amy', 'Santiago'],
	['Karen', 'Peralta'],
	['Victor', 'Santiago'],
	['Roger', 'Peralta'],
	['Doug', 'Judy'],
	['Rosa', 'Diaz'],
	['Adrian', 'Pimento'],
	['Oscar', 'Diaz'],
	['Terry', 'Jeffords'],
	['Sharon', 'Jeffords'],
	['Lacey', 'Jeffords'],
	['Cagney', 'Jeffords'],
	['Charles', 'Boyle'],
	['Vivian', 'Ludley'],
	['Genevieve', 'Mirren-Carter'],
	['Lynn', 'Boyle'],
	['Ray', 'Holt'],
	['Kevin', 'Cozner'],
	['Gina', 'Linetti'],
	['Michael', 'Hitchcock'],
	['Madeline', 'Wuntch'],
	['James', 'Holden'],
	['Naomi', 'Nagata'],
	['Alex', 'Kamal'],
	['Amos', 'Burton'],
	['Fred', 'Johnson'],
	['Theresa', 'Yao'],
	['Theresa', 'Yao'],
	['Sadavir', 'Errinwright'],
	['Josephus Aloisus', 'Miller'],
	['Chrisjen', 'Avasarala'],
	['Marco', 'Inaros'],
	['Vaelin', 'Al Sorna'],
	['Alornis', 'Al Sorna'],
	['Malcius', 'Al Nieren'],
	['Lyrna', 'Al Nieren'],
	['Janus', 'Al Nieren'],
	['Dahrena', 'Al Myrna'],
	['Adal', 'Zenu'],
	['Orven', 'Al Melna'],
	['Insha', 'ka Forna'],
	['Nortah', 'Al Sendahl'],
	['Sella', 'Al Sendahl'],
	['Sanesh', 'Poltar'],
	['Caenis', 'Al Nysa'],
	['Sentes', 'Mustor'],
	['Reva', 'Mustor'],
	['Arentes', 'Varnor'],
	['Bren', 'Antesh'],
	['Ermund', 'Lewen'],
	['Hughlin', 'Banders'],
	['Ulice', 'Banders'],
	['Arendil', 'Banders'],
	['Illian', 'Al Jervin'],
	['Alcius', 'Al Hestian'],
	['Lakrhil', 'Al Hestian'],
	['Janril', 'Norin'],
	['Elora', 'Norin'],
	['Verniers Alishe', 'Someren'],
	['Fornella', 'Av Entril Av Tokrev'],
	['Atheran', 'Ell-Nestra'],
	['Carval', 'Ell-Nurin'],
	['Nersus', 'Sil Nin'],
	['Hera', 'Drakil'],
	['Iltis', 'Al Adral'],
	['Benten', 'Al Grey Gull'],
	['Orena', 'Al Vardrian'],
	['Murel', 'Al Harten'],
	['Allern', 'Varesh'],
	['Elera', 'Al Mendah'],
	['Dendrish', 'Hendal'],
	['Benril', 'Lernial'],
	['Aluran Maxtor', 'Selsus'],
	['Astorek', 'Anvir'],
	['Del', 'Spooner'],
	['Susan', 'Calvin'],
	['Alfred', 'Lanning'],
	['Lawrence', 'Robertson'],
	['John', 'Bergin'],
	['Lyra', 'Belacqua'],
	['Marisa', 'Coulter'],
	['Lord', 'Asriel'],
	['Will', 'Parry'],
	['Carlo', 'Boreal'],
	['Mary', 'Malone'],
	['Iorek', 'Byrnison'],
	['Lee', 'Scoresby'],
	['Serafina', 'Pekkala'],
	['Roger', 'Parslow'],
	['John', 'Parry'],
	['Stanislaus', 'Grumman'],
	['John', 'Faa'],
	['Tony', 'Makarios'],
	['Farder', 'Coram'],
	['Cithrin', 'bel Sarcour'],
	['Marcus', 'Wester'],
	['Clara Annalise', 'Kalliam'],
	['Vincen', 'Coe'],
	['Kitap', 'rol Keshmet'],
	['Callon', 'Cane'],
	['Yardem', 'Hane'],
	['Barriath', 'Kalliam'],
	['Jorey', 'Kalliam'],
	['Sabiha', 'Skestinin'],
	['Canl', 'Daskellin'],
	['Sanna', 'Daskellin'],
	['Namen', 'Flor'],
	['Noyel', 'Flor'],
	['Ernst', 'Mecelli'],
	['Curtin', 'Issandrian'],
	['Fallon', 'Broot'],
	['Carol', 'Dannien'],
	['Komme', 'Medean'],
	['Lauro', 'Medean'],
	['Paerin', 'Clark'],
	['Feldin', 'Maas'],
	['Phelia', 'Maas'],
	['Drakkis', 'Stormcrow'],
	['Canl', 'Daskellin'],
	['Lizanne', 'Lethridge'],
	['Lodima', 'Bondersil'],
	['Jermayah', 'Tollermine'],
	['Wulfcot', 'Trumane'],
	['Jebneel', 'Lemhill'],
	['Boswald', 'Tottleborn'],
	['Dravin', 'Talmant'],
	['Naytanil', 'Bozware'],
	['Claydon', 'Torcreek'],
	['Braddon', 'Torcreek'],
	['Fredabel', 'Torcreek'],
	['Loriabeth', 'Torcreek'],
	['Cwentun', 'Skaggerhill'],
	['Visandra', 'Foxbine'],
	['Zenida', 'Okanas'],
	['Akina', 'Okanas'],
	['Arshav', 'Okanas'],
	['Ethilda', 'Okanas'],
	['Ethelynne', 'Drystone'],
	['Orwinn', 'Scriberson'],
	['Seydell', 'Keelman'],
	['Leonis', 'Akiv Artonin'],
	['Tekela', 'Akiv Artonin'],
	['Arberus Lek', 'Hakimas'],
	['Kaylib', 'Tragerhorn'],
	['Erric', 'Firpike'],
	['Rikki', 'Stormgren'],
	['Rupert', 'Boyce'],
	['Jan', 'Rodricks'],
	['George', 'Greggson'],
	['Jean', 'Greggson'],
	['Jeffrey', 'Greggson'],
	['Jennifer Anne', 'Greggson'],
	['William', 'Laurence'],
	['Jane', 'Roland'],
	['Catherine', 'Harcourt'],
	['Thomas', 'Riley'],
	['Emily', 'Roland'],
	['John', 'Granby'],
	['Edward', 'Howe'],
	['Bertram', 'Woolvey'],
	['Edith', 'Galman'],
	['Maia', 'Drazhar'],
	['Chenelo', 'Drazharan'],
	['Idra', 'Drazhar'],
	['Csevet', 'Aisava'],
	['Deret', 'Beshelar'],
	['Cala', 'Athmaza'],
	['Arbelan', 'Drazharan'],
	['Vedero', 'Drazhin'],
	['Ino', 'Drazhin'],
	['Thara', 'Celehar'],
	['Csethiro', 'Ceredin'],
	['Olvaris', 'Curnar'],
	['Aro', 'Danivaran'],
	['Cora', 'Drazhar'],
	['Vorzhis', 'Gormened'],
	['Nadaro', 'Gormened'],
	['Verer', 'Orthema'],
	['Reneian', 'Orthemo'],
	['Leilis', 'Athmaza'],
	['Marianne', 'Pinhoe'],
	['Joe', 'Pinhoe'],
	['Hiroaki', 'Protagonist'],
	['Da5id', 'Meier'],
	['Juanita', 'Marquez'],
	['John', 'Oldman'],
	['Linda', 'Murphy'],
	['Will', 'Gruber'],
	['David', 'Goldfarb'],
	['Ludmila', 'Gorbunova'],
	['Jens', 'Larssen'],
	['Barbara', 'Larssen'],
	['Moishe', 'Russie'],
	['Rivka', 'Russie'],
	['Reuven', 'Russie'],
	['Sam', 'Yeager'],
	['Liu', 'Han'],
	['Bobby', 'Fiore'],
	['Lucille', 'Potter'],
	['Ken', 'Embry'],
	['George', 'Bagnall'],
	['Avice Benner', 'Cho'],
	['Gwenna', 'Sharpe'],
	['Rampuri', 'Tan'],
	['Kaden', 'Malkeenian'],
	['Valyn', 'Malkeenian'],
	['Adare', 'Malkeenian'],
	['Ha Lin', 'Cha'],
	['Laith', 'Atenkor'],
	['Annick', 'Frencha'],
	['Ran', 'il Tornja'],
	['David', 'Charleston'],
	['Megan', 'Tarash'],
	['Abraham', 'Desjardins'],
	['Steven', 'Hyde'],
	['Donna', 'Pinciotti '],
	['Jackie', 'Burkhart'],
	['Kitty', 'Forman'],
	['Bob', 'Pinciotti'],
	['Michael', 'Kelso'],
	['Eric', 'Forman'],
	['Midge', 'Pinciotti'],
	['Leo', 'Chingkwake'],
	['Laurie', 'Forman'],
	['Casey', 'Kelso'],
	['Edna', 'Hyde'],
	['Bud', 'Hyde'],
	['Alex', 'Moran'],
	['Craig', 'Shilo'],
	['Radon', 'Randell'],
	['Mary Jo', 'Cacciatore'],
	['Debra', 'Simon'],
	['Harmon', 'Tedesco'],
	['Walter', 'Sherman'],
	['Leo', 'Knox'],
	['Isabel', 'Zambada'],
	['Willa', 'Monday'],
	['Timo', 'Proud'],
	['Colt', 'Bennett'],
	['Beau', 'Bennett'],
	['Mary', 'Roth'],
	['Heather', 'Roth'],
	['Darlene', 'Roth'],
	['Tanya', 'Showers'],
	['Bill', 'Jensen'],
	['Ed', 'Bishop'],
	['Clive', 'Babineaux'],
	['Dr. Ravi', 'Chakrabarti'],
	['Major', 'Lilywhite'],
	['Peyton', 'Charles'],
	['Eva', 'Moore'],
	['Evan', 'Moore'],
	['Julien', 'Dupont'],
	['Lowell', 'Tracey'],
	['Jorg', 'Ancrath'],
	['Olidan', 'Ancrath'],
	['Sareth', 'Scorron'],
	['Kathrine', 'Ap Scorron'],
	['William', 'Ancrath'],
	['Jalan', 'Kendrath'],
	['Snorri', 'Ver Snagason'],
	['Ashby', 'Santoso'],
	['Sissix', 'Seshkethet'],
	['Rosemarie', 'Harper'],
	['Dazen', 'Guile'],
	['Gavin', 'Guile'],
	['Andross', 'Guile'],
	['Felia', 'Guile'],
	['Karris', 'Whiteoak'],
	['Zymun', 'Whiteoak'],
	['Corvan', 'Danavis'],
	['Aliviana', 'Danavis'],
	['Janus', 'Borig'],
	['Perrin', 'Myerson'],
	['Eirene', 'Malargos'],
	['Gill', 'Greyling'],
	['Gavin', 'Greyling'],
	['Katalina', 'Delauria'],
	['Antonius', 'Malargos'],
	['Anjali', 'Gates'],
	['Derwyn', 'Aleph'],
	['Eli', 'Monpress'],
	['Josef', 'Liechten'],
	['Guiseppe', 'Monpress'],
	['Miranda', 'Lyonette'],
	['Heinricht', 'Slorn'],
	['Pele', 'Slorn'],
	['Nivel', 'Slorn'],
	['Etmon', 'Banage'],
	['Berek', 'Sted'],
	['Melanie', 'Smooter'],
	['Jake', 'Perry'],
	['Andrew', 'Hennings'],
	['Kate', 'Hennings'],
	['Pearl', 'Smooter'],
	['Earl', 'Smooter'],
	['Stella Kay', 'Perry'],
	['Bobby Ray', 'Bailey'],
	['Jean-Luc', 'Picard'],
	['William', 'Riker'],
	['Geordi', 'La Forge'],
	['Tasha', 'Yar'],
	['Beverly', 'Crusher'],
	['Deanna', 'Troi'],
	['Noonien', 'Soong'],
	['Wesley', 'Crusher'],
	['Lwaxana', 'Troi'],
	['Ro', 'Laren'],
	['Kira', 'Nerys'],
	['Reginald', 'Barclay'],
	['Benjamin', 'Sisko'],
	['Julian', 'Bashir'],
	['Jadzia', 'Dax'],
	['Jake', 'Sisko'],
	['Elim', 'Garak'],
	['Kasidy', 'Yates'],
	['Kathryn', 'Janeway'],
	['Tom', 'Paris'],
	['Harry', 'Kim'],
	['Lewis', 'Zimmerman'],
	['Michael', 'Burnham'],
	['Ash', 'Tyler'],
	['Paul', 'Stamets'],
	['Sylvia', 'Tilly'],
	['Gabriel', 'Lorca'],
	['Philippa', 'Georgiou'],
	['Charles', 'Xavier'],
	['Erik', 'Lehnsherr'],
	['Ororo', 'Munroe'],
	['Jean', 'Grey'],
	['Scott', 'Summers'],
	['Bobby', 'Drake'],
	['James', 'Howlett'],
	['William', 'Stryker'],
	['Kurt', 'Wagner'],
	['Robert', 'Kelly'],
	['Cain', 'Marko'],
	['Kitty', 'Pryde'],
	['Warren', 'Worthington III'],
	['Victor', 'Creed'],
	['Moira', 'MacTaggert'],
	['Shingen', 'Yashida'],
	['Mariko', 'Yashida'],
	['Kenuichio', 'Harada'],
	['Bolivar', 'Trask'],
	['Peter', 'Maximoff'],
	['Wade', 'Wilson'],
	['Vanessa', 'Carlysle'],
	['Francis', 'Freeman'],
	['Jack', 'Hammer'],
	['Ellie', 'Phimister'],
	['En', 'Sabah Nur'],
	['Alex', 'Summers'],
	['Jubilation', 'Lee'],
	['Cassie', 'Sullivan'],
	['Thomas', 'Parish'],
	['Evan', 'Walker'],
	['Sam', 'Sullivan'],
	['Alexander', 'Vosch'],
	['Curtis', 'Everett'],
	['Namgoong', 'Minsu'],
	['Logan', 'Cale'],
	['Herbal', 'Thought'],
	['Kendra', 'Maibaum'],
	['Donald', 'Lydecker'],
	['Asha', 'Barlow'],
	['Ames', 'White'],
	['Matt', 'Sung'],
	['Elizabeth', 'Renfro'],
	['Dan', 'Vogelsang'],
	['Walter', 'Eastep'],
	['Jonas', 'Cale'],
	['Bruno', 'Anselmo'],
	['Edgar', 'Sonrisa'],
	['Nathan', 'Herrero'],
	['Happy', 'Gilmore'],
	['Shooter', 'McGavin'],
	['Virginia', 'Venit'],
	['Andy', 'Dufresne'],
	['Samuel', 'Norton'],
	['Byron', 'Hadley'],
	['Tommy', 'Williams']
];

export const randomStreetPrefixes: string[] = [
	'',
	'N ',
	'W ',
	'E ',
	'S ',
	'NE ',
	'NW ',
	'SE ',
	'SW '
];

// from https://www.washingtonpost.com/blogs/govbeat/wp/2015/03/06/these-are-the-most-popular-street-names-in-every-state/
export const randomStreetNamesByState: { [state: string]: string[] } = {
	Alabama: ['Dogwood', '2nd', '1st', 'Pine', '3rd', '4th', 'Oak', 'Park', '5th', 'Jackson'],
	Alaska: ['2nd', '3rd', '1st', 'Airport', 'Spruce', '4th', 'Birch', '5th', 'Main', 'Willow'],
	Arizona: [
		'Apache',
		'1st',
		'Palo Verde',
		'Mesquite',
		'Sunset',
		'2nd',
		'Navajo',
		'3rd',
		'Quail',
		'4th'
	],
	Arkansas: ['Oak', 'Main', 'Park', 'Pine', '2nd', 'Cedar', 'Elm', 'Maple', '3rd', 'Dogwood'],
	California: [
		'Park',
		'Oak',
		'Pine',
		'Sunset',
		'Cedar',
		'Willow',
		'1st',
		'Cypress',
		'2nd',
		'Redwood'
	],
	Colorado: ['Aspen', '2nd', '1st', 'Spruce', 'Cedar', 'Park', '3rd', '4th', '5th', 'Columbine'],
	Connecticut: [
		'Park',
		'Laurel',
		'Maple',
		'Lake',
		'Sunset',
		'Meadow',
		'West',
		'Hillside',
		'Evergreen',
		'Ridge'
	],
	Delaware: [
		'Holly',
		'Park',
		'Dogwood',
		'Maple',
		'2nd',
		'Church',
		'Pine',
		'Delaware',
		'Willow',
		'Bay'
	],
	Florida: ['2nd', '6th', '4th', '5th', '1st', '3rd', '7th', '8th', '10th', '9th'],
	Georgia: [
		'Dogwood',
		'Oak',
		'Pine',
		'Park',
		'Williams',
		'Magnolia',
		'Lake',
		'Lakeview',
		'Church',
		'Cedar'
	],
	Hawaii: ['Lehua', 'Kukui', '9th', '4th', 'Kahili', '11th', '12th', 'Aloha', 'Malulani', '13th'],
	Idaho: ['1st', '2nd', '3rd', 'Main', '4th', 'Park', '5th', 'Pine', 'Aspen', '6th'],
	Illinois: [
		'Park',
		'Oak',
		'Lincoln',
		'Maple',
		'1st',
		'2nd',
		'3rd',
		'Hickory',
		'Walnut',
		'Washington'
	],
	Indiana: [
		'Park',
		'County Line',
		'Maple',
		'Oak',
		'1st',
		'Walnut',
		'Main',
		'2nd',
		'Sycamore',
		'Washington'
	],
	Iowa: ['1st', '3rd', '2nd', 'Park', '4th', '5th', '6th', '7th', 'Maple', '8th'],
	Kansas: ['1st', '2nd', '3rd', '4th', '10th', '5th', '6th', 'Kansas', 'Main', 'Washington'],
	Kentucky: [
		'Maple',
		'Park',
		'Walnut',
		'Oak',
		'Main',
		'Dogwood',
		'Johnson',
		'Smith',
		'Wilson',
		'2nd'
	],
	Louisiana: ['Magnolia', 'Oak', '3rd', '2nd', 'Pine', 'Main', '6th', 'Park', 'Cypress', '1st'],
	Maine: [
		'Main',
		'Shore',
		'Birch',
		'Sunset',
		'Spruce',
		'Cedar',
		'Maple',
		'Evergreen',
		'Pine',
		'Hemlock'
	],
	Maryland: [
		'Park',
		'Oak',
		'Maple',
		'Cedar',
		'Holly',
		'Pine',
		'Washington',
		'Church',
		'Walnut',
		'1st'
	],
	Massachusetts: [
		'Park',
		'Maple',
		'Highland',
		'Oak',
		'Cedar',
		'Pine',
		'Laurel',
		'Pleasant',
		'Hillside',
		'Lincoln'
	],
	Michigan: ['Maple', 'Park', 'Lake', 'Pine', 'Oak', 'Cedar', '2nd', 'Lakeview', '1st', 'Birch'],
	Minnesota: ['1st', '3rd', '2nd', '4th', '5th', 'Park', '6th', '7th', '10th', '8th'],
	Mississippi: [
		'Magnolia',
		'Oak',
		'Dogwood',
		'Pine',
		'2nd',
		'Jackson',
		'Johnson',
		'Church',
		'3rd',
		'1st'
	],
	Missouri: ['Park', 'Oak', 'Maple', 'Walnut', 'Cedar', 'Elm', '2nd', '3rd', 'Main', 'Hickory'],
	Montana: ['2nd', '1st', '3rd', '4th', '5th', '6th', 'Main', '7th', 'Park', '8th'],
	Nebraska: ['1st', '2nd', '3rd', '4th', 'Park', '5th', 'Main', '6th', 'A', '8th'],
	Nevada: ['1st', 'Park', '2nd', '5th', 'Canyon', '3rd', 'Cottonwood', 'Cedar', 'Pioneer', '4th'],
	'New Hampshire': [
		'Maple',
		'Spruce',
		'Hemlock',
		'Pine',
		'Park',
		'River',
		'Shore',
		'Birch',
		'Sunset',
		'Mountain View'
	],
	'New Jersey': [
		'Park',
		'Oak',
		'Maple',
		'Cedar',
		'Washington',
		'Laurel',
		'Pine',
		'Lincoln',
		'Willow',
		'Holly'
	],
	'New Mexico': [
		'Cedar',
		'Pinon',
		'2nd',
		'Pine',
		'Juniper',
		'Sunset',
		'Aspen',
		'Cottonwood',
		'4th',
		'Main'
	],
	'New York': ['Park', 'Maple', 'Lake', 'Sunset', 'Pine', 'Main', 'Oak', 'North', '1st', 'River'],
	'North Carolina': [
		'Dogwood',
		'Park',
		'Oak',
		'Pine',
		'Ridge',
		'Cedar',
		'Maple',
		'Sunset',
		'Church',
		'2nd'
	],
	'North Dakota': ['2nd', '1st', '3rd', '4th', '6th', '5th', '7th', 'Main', '8th', '10th'],
	Ohio: ['Park', 'Maple', 'Oak', 'Main', 'Walnut', 'North', 'West', 'Lincoln', '2nd', 'Elm'],
	Oklahoma: ['Oak', '1st', '3rd', 'Cedar', '2nd', 'County Line', '4th', 'Broadway', 'Elm', '5th'],
	Oregon: ['2nd', '3rd', '1st', '4th', '7th', '5th', 'Park', 'Cedar', '6th', '8th'],
	Pennsylvania: ['Maple', 'Park', 'Oak', 'Pine', '2nd', '3rd', 'Church', 'Ridge', 'Cherry', '1st'],
	'Rhode Island': [
		'Park',
		'Shore',
		'Maple',
		'Highland',
		'Pine',
		'Cedar',
		'Meadow',
		'Narragansett',
		'River',
		'Wood'
	],
	'South Carolina': [
		'Park',
		'Dogwood',
		'Oak',
		'Pine',
		'Cedar',
		'Smith',
		'Church',
		'Hampton',
		'Magnolia',
		'Maple'
	],
	'South Dakota': ['1st', '2nd', '3rd', '4th', '5th', 'Main', '6th', '7th', 'Park', '8th'],
	Tennessee: [
		'Dogwood',
		'Oak',
		'Park',
		'Maple',
		'Church',
		'Main',
		'Cedar',
		'Smith',
		'Hickory',
		'Sunset'
	],
	Texas: ['Park', 'Oak', '2nd', '1st', 'Pecan', '3rd', 'Cedar', '4th', 'Main', '5th'],
	Utah: [
		'Main',
		'Park',
		'Aspen',
		'Cottonwood',
		'Canyon',
		'Center',
		'Sunset',
		'S 400',
		'S 100',
		'N 400'
	],
	Vermont: [
		'Park',
		'Mountain View',
		'Hill',
		'Maple',
		'Birch',
		'Meadow',
		'River',
		'Hillside',
		'Cedar',
		'Sunset'
	],
	Virginia: ['Lee', 'Park', 'Oak', 'Cedar', 'Dogwood', 'Maple', 'Pine', 'Ridge', 'Jackson', 'Main'],
	Washington: ['3rd', '1st', '2nd', '4th', 'Park', '5th', '8th', '7th', '6th', '10th'],
	'West Virginia': [
		'Maple',
		'Park',
		'Walnut',
		'1st',
		'Oak',
		'3rd',
		'2nd',
		'Pine',
		'River',
		'Orchard'
	],
	Wisconsin: ['Park', 'Maple', 'Pine', 'Oak', 'River', 'Lake', '1st', 'Elm', 'County Line', '2nd'],
	Wyoming: ['2nd', 'Park', '3rd', '1st', '4th', '6th', 'Aspen', 'Cedar', '5th', 'Cottonwood']
};

export const randomStreetSuffixes: string[] = [
	'Rd',
	'St',
	'Cty Rd',
	'Ave',
	'Dr',
	'Ln',
	'Blvd',
	'Ct',
	'Way'
];

// from https://en.wikipedia.org/wiki/List_of_largest_cities_of_U.S._states_and_territories_by_population
export const randomTowns: { [state: string]: string[] } = {
	Alabama: ['Huntsville', 'Birmingham', 'Montgomery', 'Mobile', 'Tuscaloosa'],
	Alaska: ['Anchorage', 'Juneau', 'Fairbanks', 'Wasilla', 'Sitka'],
	Arizona: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale'],
	Arkansas: ['Little Rock', 'Fayetteville', 'Fort Smith', 'Springdale', 'Jonesboro'],
	California: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno'],
	Colorado: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood'],
	Connecticut: ['Bridgeport', 'Stamford', 'New Haven', 'Hartford', 'Waterbury'],
	Delaware: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna'],
	Florida: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg'],
	Georgia: ['Atlanta', 'Columbus', 'Augusta', 'Macon', 'Savannah'],
	Hawaii: ['Honolulu', 'East Honolulu', 'Pearl City', 'Hilo', 'Kailua'],
	Idaho: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Caldwell'],
	Illinois: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Rockford'],
	Indiana: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'],
	Iowa: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'],
	Kansas: ['Wichita', 'Overland Park', 'Kansas City', 'Olathe', 'Topeka'],
	Kentucky: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'],
	Louisiana: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'],
	Maine: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn'],
	Maryland: ['Baltimore', 'Columbia', 'Germantown', 'Silver Spring', 'Waldorf'],
	Massachusetts: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'],
	Michigan: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor'],
	Minnesota: ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington'],
	Mississippi: ['Jackson', 'Gulfport', 'Southaven', 'Biloxi', 'Hattiesburg'],
	Missouri: ['Kansas City', 'Saint Louis', 'Springfield', 'Columbia', 'Independence'],
	Montana: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte'],
	Nebraska: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'],
	Nevada: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Paradise'],
	'New Hampshire': ['Manchester', 'Nashua', 'Concord', 'Dover', 'Rochester'],
	'New Jersey': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison'],
	'New Mexico': ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell'],
	'New York': ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse'],
	'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'],
	'North Dakota': ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'],
	Ohio: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'],
	Oklahoma: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'],
	Oregon: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro'],
	Pennsylvania: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'],
	'Rhode Island': ['Providence', 'Cranston', 'Warwick', 'Pawtucket', 'East Providence'],
	'South Carolina': ['Charleston', 'Columbia', 'North Charleston', 'Mount Pleasant', 'Rock Hill'],
	'South Dakota': ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown'],
	Tennessee: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'],
	Texas: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth'],
	Utah: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem'],
	Vermont: ['Burlington', 'South Burlington', 'Rutland', 'Barre', 'Montpelier'],
	Virginia: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Newport News'],
	Washington: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
	'West Virginia': ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'],
	Wisconsin: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'],
	Wyoming: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs']
};

// from https://github.com/faker-ruby/faker/blob/aa31845ed54c25eb2638d716bfddf59771b502aa/lib/locales/en/address.yml
export const randomZips: { [state: string]: string } = {
	Alabama: '350**',
	Alaska: '995**',
	Arizona: '850**',
	Arkansas: '717**',
	California: '900**',
	Colorado: '800**',
	Connecticut: '061**',
	Delaware: '198**',
	Florida: '322**',
	Georgia: '301**',
	Hawaii: '967**',
	Idaho: '832**',
	Illinois: '600**',
	Indiana: '463**',
	Iowa: '510**',
	Kansas: '666**',
	Kentucky: '404**',
	Louisiana: '701**',
	Maine: '042**',
	Maryland: '210**',
	Massachusetts: '026**',
	Michigan: '480**',
	Minnesota: '555**',
	Mississippi: '387**',
	Missouri: '650**',
	Montana: '590**',
	Nebraska: '688**',
	Nevada: '898**',
	'New Hampshire': '036**',
	'New Jersey': '076**',
	'New Mexico': '880**',
	'New York': '122**',
	'North Carolina': '288**',
	'North Dakota': '586**',
	Ohio: '444**',
	Oklahoma: '730**',
	Oregon: '979**',
	Pennsylvania: '186**',
	'Rhode Island': '029**',
	'South Carolina': '299**',
	'South Dakota': '577**',
	Tennessee: '383**',
	Texas: '798**',
	Utah: '847**',
	Vermont: '050**',
	Virginia: '222**',
	Washington: '990**',
	'West Virginia': '247**',
	Wisconsin: '549**',
	Wyoming: '831**'
};

export const randomStates: string[] = [
	'Alabama',
	'Alaska',
	'Arizona',
	'Arkansas',
	'California',
	'Colorado',
	'Connecticut',
	'Delaware',
	'Florida',
	'Georgia',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine',
	'Maryland',
	'Massachusetts',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'New Hampshire',
	'New Jersey',
	'New Mexico',
	'New York',
	'North Carolina',
	'North Dakota',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'Rhode Island',
	'South Carolina',
	'South Dakota',
	'Tennessee',
	'Texas',
	'Utah',
	'Vermont',
	'Virginia',
	'Washington',
	'West Virginia',
	'Wisconsin',
	'Wyoming'
];
